final List<Map<String, dynamic>> columnHeader = [
  {'columnName': 'Dealer Name', 'required': true},
  {'columnName': 'Dealer Email Address', 'required': true},
  {'columnName': 'Dealer Contact Number', 'required': true},
  {'columnName': 'TM Role', 'required': false},
  {'columnName': 'TM Name', 'required': false},
  {'columnName': 'TM Email Address', 'required': false},
  {'columnName': 'TM Phone Number', 'required': true},
  {'columnName': 'TM UserName', 'required': false},
  {'columnName': 'AM Role', 'required': false},
  {'columnName': 'AM Name', 'required': false},
  {'columnName': 'AM Email Address', 'required': false},
  {'columnName': 'AM Phone Number', 'required': true},
  {'columnName': 'AM UserName', 'required': false},
  {'columnName': 'NSM Role', 'required': false},
  {'columnName': 'NSM Name', 'required': false},
  {'columnName': 'NSM Email Address', 'required': false},
  {'columnName': 'NSM Phone Number', 'required': true},
  {'columnName': 'NSM UserName', 'required': false},
  {'columnName': 'NSM1 Name', 'required': false},
  {'columnName': 'NSM1 Email Address', 'required': false},
  {'columnName': 'NSM1 Phone Number', 'required': true},
  {'columnName': 'NSM1 UserName', 'required': false},
  {'columnName': 'VP Role', 'required': false},
  {'columnName': 'VP Name', 'required': false},
  {'columnName': 'VP Email Address', 'required': false},
  {'columnName': 'VP Phone Number', 'required': true},
  {'columnName': 'VP UserName', 'required': false},
  {'columnName': 'VP1 Name', 'required': false},
  {'columnName': 'VP1 Email Address', 'required': false},
  {'columnName': 'VP1 Phone Number', 'required': true},
  {'columnName': 'VP1 UserName', 'required': false},
  {'columnName': 'VP2 Name', 'required': false},
  {'columnName': 'VP2 Email Address', 'required': false},
  {'columnName': 'VP2 Phone Number', 'required': true},
  {'columnName': 'VP2 UserName', 'required': false},
  {'columnName': 'HO Role', 'required': false},
  {'columnName': 'HO Name', 'required': false},
  {'columnName': 'HO Email Address', 'required': false},
  {'columnName': 'HO Phone Number', 'required': true},
  {'columnName': 'HO UserName', 'required': false},
];
